name: Bash Linting

on:
  push:
    branches:
      - main
      - dev-lea
  pull_request:
    branches:
      - main
      - dev-lea

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bash linter
      run: sudo apt-get install -y shellcheck

    - name: Lint Bash scripts
      run: shellcheck walletRotation.sh